In [5]:
import pandas as pd

In [6]:
shotlog = "shot_logs.csv"

In [8]:
shotlogdf = pd.read_csv(shotlog)
shotlogdf.head()

,GAME_ID,MATCHUP,LOCATION,W,FINAL_MARGIN,SHOT_NUMBER,PERIOD,GAME_CLOCK,SHOT_CLOCK,DRIBBLES,...,SHOT_DIST,PTS_TYPE,SHOT_RESULT,CLOSEST_DEFENDER,CLOSEST_DEFENDER_PLAYER_ID,CLOSE_DEF_DIST,FGM,PTS,player_name,player_id
0,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,1,1,1:09,10.8,2,...,7.7,2,made,"Anderson, Alan",101187,1.3,1,2,brian roberts,203148
1,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,2,1,0:14,3.4,0,...,28.2,3,missed,"Bogdanovic, Bojan",202711,6.1,0,0,brian roberts,203148
2,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,3,1,0:00,NaN,3,...,10.1,2,missed,"Bogdanovic, Bojan",202711,0.9,0,0,brian roberts,203148
3,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,4,2,11:47,10.3,2,...,17.2,2,missed,"Brown, Markel",203900,3.4,0,0,brian roberts,203148
4,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,5,2,10:34,10.9,2,...,3.7,2,missed,"Young, Thaddeus",201152,1.1,0,0,brian roberts,203148

In [17]:
shotlogdf['GAME_CLOCK'] = pd.to_numeric(shotlogdf['GAME_CLOCK'])

ValueError: Unable to parse string "1:09" at position 0

In [19]:
import datetime
import time
x = time.strptime('11:30','%M:%S')
datetime.timedelta(hours=x.tm_hour,minutes=x.tm_min,seconds=x.tm_sec).total_seconds()

690.0

In [13]:
shotlog4 = shotlogdf.loc[(shotlogdf["PERIOD"] == 4) & 
                         (shotlogdf["SHOT_RESULT"] == "made") &
                         (shotlogdf["GAME_CLOCK"] < )
                         
                         ,:]
shotlog4.head()

,GAME_ID,MATCHUP,LOCATION,W,FINAL_MARGIN,SHOT_NUMBER,PERIOD,GAME_CLOCK,SHOT_CLOCK,DRIBBLES,...,SHOT_DIST,PTS_TYPE,SHOT_RESULT,CLOSEST_DEFENDER,CLOSEST_DEFENDER_PLAYER_ID,CLOSE_DEF_DIST,FGM,PTS,player_name,player_id
7,21400899,"MAR 04, 2015 - CHA @ BKN",A,W,24,8,4,8:00,3.4,3,...,3.5,2,made,"Plumlee, Mason",203486,2.1,1,2,brian roberts,203148
11,21400890,"MAR 03, 2015 - CHA vs. LAL",H,W,1,3,4,11:32,12.1,14,...,14.6,2,made,"Lin, Jeremy",202391,1.8,1,2,brian roberts,203148
12,21400890,"MAR 03, 2015 - CHA vs. LAL",H,W,1,4,4,8:55,4.3,2,...,5.9,2,made,"Hill, Jordan",201941,5.4,1,2,brian roberts,203148
18,21400859,"FEB 27, 2015 - CHA @ BOS",A,L,-8,5,4,10:29,20.8,0,...,24.2,3,made,"Thomas, Isaiah",202738,11.1,1,3,brian roberts,203148
25,21400845,"FEB 25, 2015 - CHA @ CHI",A,W,12,7,4,10:13,17.1,7,...,24.6,3,made,"Noah, Joakim",201149,6.0,1,3,brian roberts,203148